### ISSUE TITLE
Upload Directory doesn't copy its subdirectories

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#41] opened 2015-05-04 02:00 UTC
When I use the "Upload Directory" command, it only uploads the topmost level of the selected directory. If it contained subdirectories, their contents won't be uploaded.

**Comment by whoozle** [comment] 2015-05-04 07:54
this is duplicate of #2. I'm in a process of fixing this.

**Closed by whoozle** 2015-05-04 07:54 UTC
