### ISSUE TITLE
[FR]FUSE support for macOS?

### ISSUE THREAD

**Issue by yurikoles** [whoozle/android-file-transfer-linux#209] opened 2018-11-06 13:35 UTC
We have a FUSE for mac via [osxfuse](https://osxfuse.github.io/), please add support for it.

**Comment by whoozle** [comment] 2018-11-06 13:55
Unfortunately I don't have any Mac hardware around.

**Comment by whoozle** [comment] 2018-11-06 13:59
Duplicate of #114 
Someone told that he was able to build and run it. Could you investigate please?

**Comment by whoozle** [comment] 2018-11-06 14:00
Argh, it was just macosx build, no fuse.

**Closed by whoozle** 2018-11-06 14:00 UTC

**Comment by yurikoles** [comment] 2018-11-06 14:04
@whoozle please reopen.

**Comment by whoozle** [comment] 2018-11-06 14:05
Why? #114 is still open, it's about the same thing.
