### ISSUE TITLE
Even though it is an appimage it still requires these programmes to be installed

### ISSUE THREAD

**Issue by viveksray17** [whoozle/android-file-transfer-linux#316] opened 2022-09-21 18:05 UTC
The appimage didn't launch until these programs were installed. `gvfs-mtp` and `mtpfs` are the two programs that need to be installed. It would be better if you include these dependencies into the appimage

**Comment by whoozle** [comment] 2022-09-23 08:54
duplicate of #315, let's merge them together there

**Closed by whoozle** 2022-09-23 08:54 UTC
